### ISSUE TITLE
Лишние свойства в объектах

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/cv-project#10]
Зачем тебе "www"? разве нельзя избавиться от этого свойства, и задать target и rel  для всех имеющихся ссылок?

![image](https://user-images.githubusercontent.com/25764783/55930836-56340e00-5c4d-11e9-934e-2a49a5bf164d.png)

**Comment by pasha-zolotukhin** [comment]
Даже для телефона и почты?

**Comment by Frolikow** [comment]
> Ну в принципе можно наверное...
Можно
