### ISSUE TITLE
Запуск сервера

### ISSUE THREAD

**Issue by Zarwlar** [pasha-zolotukhin/cv-project#11]
npm run server пытается стартануть проект на 80 порту, а он является служебным, т.е. для запуска проекта нужно использовать sudo. Необходимости запускать проект на служебном порту в dev версии нет, поэтому порт нужно сменить на неслужебный (обычно это 8000, 8080, 3000, 3030)

**Comment by pasha-zolotukhin** [comment]
Оставил порт по умолчанию (8080).
