### ISSUE TITLE
perfect pixel

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/cv-project#7]
[начало](https://github.com/pasha-zolotukhin/cv-project/issues/2)
Можешь плиз показать скрины своей страницы с перфект пикселем?)

**Comment by pasha-zolotukhin** [comment]
После смены шрифта пиксель перфект конечно же поехал)

**Comment by Frolikow** [comment]
вообщем к чему это все было) на твоих линиях нужно найти иное решение. Куча захардкоженых отступов - плохое решение

**Comment by pasha-zolotukhin** [comment]
а если просто всем дать одинаковый стиль и пожертвовать пикселями?

**Comment by Frolikow** [comment]
да, давай.
на перфект пиксель потом посмотрим насколько расхождения

**Comment by pasha-zolotukhin** [comment]
получается сюда я комичу исправленный пиксель перфект или то что с линиями связано?

**Comment by pasha-zolotukhin** [comment]
> Можешь плиз показать скрины своей страницы с перфект пикселем?)

Это после удаления section__title и section__line
![pp](https://user-images.githubusercontent.com/26360624/55799073-b5cdd480-5afa-11e9-9b0b-a31a8411a546.png)

**Comment by Frolikow** [comment]
Нормально, главное что код стал значительно чище
