### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/cv-project#8]
Желательно делать деструктуризацию, для удобства и избавления от повторения, как, например, здесь:
![image](https://user-images.githubusercontent.com/25764783/55851581-78f9f000-5b83-11e9-9e28-e4adca7d0314.png)

**Comment by pasha-zolotukhin** [comment]
Не понял, что имеется в виду?

**Comment by Frolikow** [comment]
вот здесь нагляднее, в объекте много разных свойств 

![image](https://user-images.githubusercontent.com/25764783/55868685-2b937800-5baf-11e9-8a94-a3b1e84ffe10.png)

> Вот так?
> const img = options.img || {};
в целом да, попробуй и посмотрим  что получиться

**Comment by Frolikow** [comment]
а если в подобных местах избавиться от option.type?
например заменив новую переменную type на что-то более подходящее по смыслу к этой переменной("что в ней храниться?"). 
![image](https://user-images.githubusercontent.com/25764783/55879983-02341580-5bca-11e9-845b-5b33c109123f.png)

**Comment by pasha-zolotukhin** [comment]
Не понял что имелось в виду.

**Comment by Frolikow** [comment]
у тебя в новой переменной type что храниться? строка с названием класса для какого-то элемента. но почему тогда переменная - дословно "тип"? понимаешь о чем я?

**Comment by pasha-zolotukhin** [comment]
В смысле поменять type на icon?

**Comment by Frolikow** [comment]
а icon тут при чем?

**Comment by pasha-zolotukhin** [comment]
Это модификатор, который отвечает за стили у разных блоков profile, contact, skills и т.д.) Изначально я так сделал, чтобы блоки совпадали с пиксель перфектом.
![Снимок](https://user-images.githubusercontent.com/26360624/55940647-be451d00-5c6a-11e9-820d-e9413efd1568.PNG)

**Comment by Frolikow** [comment]
про icon понял, здесь он не при чем)
давай по порядку
![image](https://user-images.githubusercontent.com/25764783/55940949-635ff580-5c6b-11e9-8ea9-1667cafcd634.png)

**Comment by pasha-zolotukhin** [comment]
> Это модификатор, который отвечает за стили у разных блоков profile, contact, skills и т.д.) Изначально я так сделал, чтобы блоки совпадали с пиксель перфектом.

До этого там еще стили для линий и тайтла были.

**Comment by Frolikow** [comment]
Конкретно сейчас, в текущем коде, объясни что в переменной type))

**Comment by pasha-zolotukhin** [comment]
Тип section)
Он только за стили отвечает. Не знаю что еще сказать.

**Comment by Frolikow** [comment]
давай проще рассуждать) 
есть переменная type
чему в она равна, какое значение у нее?

**Comment by pasha-zolotukhin** [comment]
"profile", "contact", "skill", "education", "experience" и "software".

**Comment by Frolikow** [comment]
конкретно вот тут?
![image](https://user-images.githubusercontent.com/25764783/55943330-98227b80-5c70-11e9-9f4d-ece21e988b62.png)
type = "profile", "contact", "skill", "education", "experience" и "software"?

**Comment by pasha-zolotukhin** [comment]
не, тут любое значение может лежать) но должна принимать вышеперечисленные.

**Comment by Frolikow** [comment]
именно здесь какое у нее значени?)

**Comment by pasha-zolotukhin** [comment]
ну любое же, я через параметр ее передаю)

**Comment by Frolikow** [comment]
да я понимаю, что ты и от куда передаешь)
ладно) допустим приходит "software"


> конкретно вот тут?
> ![image](https://user-images.githubusercontent.com/25764783/55943330-98227b80-5c70-11e9-9f4d-ece21e988b62.png)
> type = "profile", "contact", "skill", "education", "experience" и "software"?

что будет в type?

**Comment by pasha-zolotukhin** [comment]
section_type_software

**Comment by Frolikow** [comment]
воот) это по своей сути что? и для чего надо?

**Comment by pasha-zolotukhin** [comment]
чтобы передать в класс блока)

**Comment by Frolikow** [comment]
так) приближаемся к истине) 
получается что это ни какой не тип, а имя класса? )

**Comment by pasha-zolotukhin** [comment]
ну это модификатор) ты мне предлагаешь поменять ее на typeClassName?

**Comment by Frolikow** [comment]
просто на className
там ведь лежит строка именно со значением класса(неважно блок или элем. или мод)
и ниже у тебя будет логично выглядеть 
class=className

**Comment by pasha-zolotukhin** [comment]
Т.е. вот так?

`const { title, type } = options;`
`let className = "section";`
`className += typeof type === "string" ? " section_type_" + type : "";`

**Comment by Frolikow** [comment]
в целом да)
не понятно зачем эта строка? для примера? 
`let className = "section";`
и зачем здесь
`className += typeof type === "string" ? " section_type_" + type : "";`
вот это `+= `, не совсем понимаю

**Comment by pasha-zolotukhin** [comment]
По аналогии как вот здесь: https://fullstack-development.gitbook.io/learn/komponentnaya-arkhitektura#chto-takoe-preprocessory

**Comment by Frolikow** [comment]
тогда да) именно так, если следовать примеру

> По аналогии как вот здесь: https://fullstack-development.gitbook.io/learn/komponentnaya-arkhitektura#chto-takoe-preprocessory

посмотри по проекту, кажется еще было такое

**Comment by pasha-zolotukhin** [comment]
Готово.
