### ISSUE TITLE
Называть блоки и элементы по смыслу, а не по внешнему виду 

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/cv-project#9]
А если надо будет квадратным сделать, придется новый миксин писать?
![image](https://user-images.githubusercontent.com/25764783/55851764-4a304980-5b84-11e9-99da-09df15fcbe03.png)

**Comment by Frolikow** [comment]
и здесь еще, у тебя получается внутри блока:
1) два item'а : period-list__li(list-item) и .period-list__item
   нужно чтоб выглядело логичнее, и чтоб глядя на классы было максимально ясно что это
2) period-list__li - это элемент с названием тега. лучше напиши полной фразой list-item. лучше будет.
![image](https://user-images.githubusercontent.com/25764783/55851815-8c598b00-5b84-11e9-8159-a07ed62763db.png)

**Comment by pasha-zolotukhin** [comment]
Мб тогда period-list__item назвать period-list__period-wrapper?

**Comment by Frolikow** [comment]
period-list__period-wrapper нормально.

вот здесь еще, почему ты решил  сделать модификатор из названия тега? 
![image](https://user-images.githubusercontent.com/25764783/55869988-d6a53100-5bb1-11e9-93e4-281fa9da8f02.png)

**Comment by Frolikow** [comment]
не надо использовать числа для именования. 
в данном случае даже left-column / right-column будет лучше
![image](https://user-images.githubusercontent.com/25764783/55870502-ec672600-5bb2-11e9-80eb-def769f362a4.png)

**Comment by pasha-zolotukhin** [comment]
Стоит ли переименовывать software-list__item в software-list__progress-bar-wrapper и skill-list__item в skill-list__power-bar-wrapper?

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/55878175-1ece4e80-5bc6-11e9-805a-c46d22d5f71b.png)
 [а как же?](https://github.com/pasha-zolotukhin/cv-project/issues/4)

**Comment by Frolikow** [comment]
> Стоит ли переименовывать software-list__item в software-list__progress-bar-wrapper и skill-list__item в skill-list__power-bar-wrapper?

будет достаточно list-item. у тебя блок "....-list" и логично что в нем будет "....-list__ list-item"

**Comment by pasha-zolotukhin** [comment]
> а как же?

Это же тип boolean у модификатора. Ссылка? Да/Нет.

**Comment by Frolikow** [comment]
> Это же тип boolean у модификатора. Ссылка? Да/Нет.
Хотя, соглашусь с тобой, тут можно рассмотреть как булево значение.
